### PR TITLE
Add Sublime Text 3 compatibility.

### PR DESCRIPTION
**Pull request by Ventero**
- Use `print` function instead of statement
- Don't import the unused `commands` module (which isn't shipped in ST3's Python distribution)
- Convert command output to a string

### CODE REVIEW

**Comment by garethsprice** [comment]
Issue getting this working in Sublime Text 3:

```
  File "GitCommitMsg in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/GitCommitMsg.sublime-package", line 32
    print 'Executing command: "%s"' % (cmd)
                                  ^
SyntaxError: invalid syntax
```

**Comment by adamkdean** [comment]
+1 for ST3 compatibility

**Comment by danielchatfield** [comment]
:+1:

**Comment by erwanjegouzo** [comment]
+1

**Comment by individual11** [comment]
+1

**Comment by clintecker** [comment]
Yes please, I haven't used ST2 in ages

**Comment by FichteFoll** [comment]
FYI, `.decode('uft-8')` will likely fail on Windows and certain UNIX setups (didn't test, but that's my experience), so it's usually safer to use `locale.getpreferredencoding()` and optionally fallback to utf-8 if that fails.

**Pull request merged**
